version: "3.9"
services:
  jellyfin:
    build:
      context: .
      dockerfile: build.dockerfile

  jellyfin-tests:
    build:
      context: .
      dockerfile: test.dockerfile
    depends_on:
      - jellyfin
    command: ["dotnet", "test", "/jellyfin"]
    volumes:
      - ./logs:/logs

  jellyfin-publish:
    image: jellyfin-publish:latest
    build:
      context: ../
      dockerfile: build.Dockerfile
      
  jellyfin-deploy:
      image: illuminaticat/jellyfin:1.1.115
      ports:
        - "8096:8096"