version: "3.9"
services:
  jellyfin:
    build:
      context: .
      dockerfile: build.dockerfile

  jellyfin-tests:
    build:
      context: .
      dockerfile: test.dockerfile
    depends_on:
      - jellyfin
    command: ["dotnet", "test", "/jellyfin"]
    volumes:
      - ./logs:/logs

  jellyfin-deploy:
    image: jellyfin/jellyfin:latest
    build:
      context: .
      dockerfile: trash.Dockerfile
      # context: ../
      # dockerfile: build.Dockerfile
    # depends_on:
    #   - jellyfin

  # jellyfin-publish:
  #   image: jellyfin/jellyfin:latest
  #   build:
  #     context: .
  #     dockerfile: publish.dockerfile
  #   depends_on:
  #     - jellyfin-deploy