 version: "3.9"
 services:
   jellyfin/jellyfin:
     image: jellyfin/jellyfin:latest
     volumes:
       - ./logs:/logs
     build: 
       context: .
       dockerfile: build.Dockerfile
   jellyfin/jellyfin-tests:
     image: jellyfin/jellyfin-tests:latest
     volumes:
       - ./logs:/logs
     build:
       context: .
       dockerfile: test.Dockerfile
     depends_on:
       - jellyfin/jellyfin
#    jellyfin/jellyfin-deploy:
#      image: jellyfin/jellyfin-deploy:latest
#      build:
#        context: .
#        dockerfile: deploy.Dockerfile
#      depends_on:
#        - jellyfin/jellyfin
#  volumes:
#    logs: