version: "3.9"
services:
  jellyfin:
    build:
      context: .
      dockerfile: build.dockerfile
  jellyfin-tests:
    build:
      context: .
      dockerfile: test.dockerfile
    depends_on:
      - jellyfin
    command: ["dotnet", "test", "/jellyfin"]
    volumes:
      - ./logs:/logs

#    jellyfin/jellyfin-deploy:
#      image: jellyfin/jellyfin-deploy:latest
#      build:
#        context: .
#        dockerfile: deploy.Dockerfile
#      depends_on:
#        - jellyfin/jellyfin
#  volumes:
#    logs: